services:
    backend:
        image: gw2tp-backend
        container_name: gw2tp-backend
        build:
            context: .
            dockerfile: backend/Dockerfile
        ports:
            - "8000:8000"

    frontend:
        image: gw2tp-frontend
        container_name: gw2tp-frontend
        build:
            context: .
            dockerfile: frontend/Dockerfile
        ports:
            - "5000:5000"
        environment:
            - BACKEND_URL=http://backend:8000
