services:
    backend:
        image: gw2tp-backend
        container_name: gw2tp-backend
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - "8000:8000"

    frontend:
        image: gw2tp-frontend
        container_name: gw2tp-frontend
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - "5000:5000"
