FROM mcr.microsoft.com/devcontainers/base:noble

RUN apt-get update && \
    apt-get install -y \
    python-is-python3 \
    pip \
    python3.12 \
    python3.12-venv \
    libpython3.12-dev \
    git
